#ifndef __PLATFORM_CONFIG_H_
#define __PLATFORM_CONFIG_H_

#define UART_BAUD 115200

#define STDOUT_IS_UARTLITE

#define PLATFORM_EMAC_BASEADDR XPAR_ETHERNET_LITE_BASEADDR

#define PLATFORM_TIMER_BASEADDR XPAR_AXI_TIMER_0_BASEADDR
#define PLATFORM_TIMER_INTERRUPT_INTR XPAR_MICROBLAZE_0_INTC_AXI_TIMER_0_INTERRUPT_INTR
#define PLATFORM_TIMER_INTERRUPT_MASK (1 << XPAR_MICROBLAZE_0_INTC_AXI_TIMER_0_INTERRUPT_INTR)

#ifdef __PPC__
#define CACHEABLE_REGION_MASK 0x80800400
#endif

#endif
